# Generated by Django 2.2.5 on 2021-11-17 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meibo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('simei', models.CharField(max_length=50, verbose_name='氏名')),
                ('simei_kana', models.CharField(max_length=50)),
                ('email_addr', models.CharField(max_length=50)),
                ('seibetu', models.CharField(max_length=10)),
                ('tanjo_bi', models.DateField()),
                ('blood_gata', models.CharField(max_length=5)),
                ('chiiki', models.CharField(max_length=50)),
                ('phone_bango', models.CharField(max_length=10)),
            ],
        ),
    ]
